apiVersion: v1
kind: Namespace
metadata:
  name: python
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: python
  labels:
    app: my-python-deployments
  name: my-python-deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-deployments
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-python-deployments
    spec:
      containers:
      - image: amuldevopstools.azurecr.io/python_jenkins:v2
        name: my-python-app-latests
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acrsecret

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbXVsZGV2b3BzdG9vbHMuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImFtdWxkZXZvcHN0b29scyIsInBhc3N3b3JkIjoiRFJ6NmxMTFZoMmhicEFySHBCWjNjbkVUSnVwWjdvMXpwcG4xNHd5RXdmK0FDUkFNV2VPdSIsImF1dGgiOiJZVzExYkdSbGRtOXdjM1J2YjJ4ek9rUlNlalpzVEV4V2FESm9ZbkJCY2tod1Fsb3pZMjVGVkVwMWNGbzNiekY2Y0hCdU1UUjNlVVYzWml0QlExSkJUVmRsVDNVPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2024-12-10T10:02:58Z"
  name: acrsecret
  namespace: python
  resourceVersion: "56170"
  uid: 916515f3-e24a-4697-9c26-98226c7d634a
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-service
  namespace: python
spec:
  type: NodePort      
  selector:
    app: my-python-deployments
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30011