name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: azure/docker-login@v2
        with:
          login-server: amuldevopstools.azurecr.io
          username: amuldevopstools
          password: DRz6lLLVh2hbpArHpBZ3cnETJupZ7o1zppn14wyEwf+ACRAMWeOu

      - name: Build and push Docker image
        run: |
          docker build  -t amuldevopstools.azurecr.io/python_gitaction:v1 ./python-gitact
          docker push amuldevopstools.azurecr.io/python_gitaction:v1
      - name: Set up Kubernetes Kubeconfig with Service Account
        run: |
          echo "${{ secrets.KUBERNETES_CA_CRT }}" > /tmp/ca.crt
          echo "${{ secrets.KUBERNETES_CLIENT_CRT }}" > /tmp/client.crt
          echo "${{ secrets.KUBERNETES_CLIENT_KEY }}" > /tmp/client.key
         
          kubectl config set-cluster Dev-Ops --server=${{ secrets.KUBERNETES_SERVER_URL }} --certificate-authority=/tmp/ca.crt
          
          kubectl config set-credentials Dev-Ops  --client-key=/tmp/client.key --client-certificate=/tmp/client.crt
          kubectl config set-context Dev-Ops --cluster=Dev-Ops --user=clusterUser_Amul-AKS_Dev-Ops
          kubectl config use-context Dev-Ops



      - name: Apply Kubernetes Deployment
        run: |
          kubectl get pods
          
          
          
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-python-deployments my-python-app-latests=amuldevopstools.azurecr.io/python_gitaction:v1