name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: azure/docker-login@v2
        with:
          login-server: amuldevopstools.azurecr.io
          username: amuldevopstools
          password: DRz6lLLVh2hbpArHpBZ3cnETJupZ7o1zppn14wyEwf+ACRAMWeOu

      - name: Build and push Docker image
        run: |
          docker build  -t amuldevopstools.azurecr.io/python_gitaction:v1 ./python-gitact
          docker push amuldevopstools.azurecr.io/python_gitaction:v1

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Apply Kubernetes Deployment
        run: |
          kubectl get nodes
          
          
          
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-python-deployments my-python-app-latests=amuldevopstools.azurecr.io/python_gitaction:v1